/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boleta;


/**
 *
 * @author CARRERA PROFESIONAL
 */
public class BOLETA2 extends javax.swing.JFrame {

    /**
     * Creates new form BOLETA2
     */
    public BOLETA2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        TEL = new javax.swing.JLabel();
        PROFESION = new javax.swing.JLabel();
        DIREC = new javax.swing.JLabel();
        APELLIDO = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        EDAD = new javax.swing.JLabel();
        GENERO = new javax.swing.JLabel();
        FECHA = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        P1 = new javax.swing.JTextField();
        P2 = new javax.swing.JTextField();
        P3 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        C3 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        ttotal = new javax.swing.JLabel();
        CALCULARTOTAL1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 440, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 190, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("R.U.C.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        NOMBRE.setForeground(new java.awt.Color(255, 255, 255));
        NOMBRE.setText("Nombre:");
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        TEL.setForeground(new java.awt.Color(255, 255, 255));
        TEL.setText("Telefono:");
        getContentPane().add(TEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        PROFESION.setForeground(new java.awt.Color(255, 255, 255));
        PROFESION.setText("Profesion");
        getContentPane().add(PROFESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        DIREC.setForeground(new java.awt.Color(255, 255, 255));
        DIREC.setText("Direccion :");
        getContentPane().add(DIREC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        APELLIDO.setForeground(new java.awt.Color(255, 255, 255));
        APELLIDO.setText("Apellido");
        getContentPane().add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 170, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 60, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 50, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 160, -1));

        EDAD.setForeground(new java.awt.Color(255, 255, 255));
        EDAD.setText("Edad :");
        getContentPane().add(EDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        GENERO.setForeground(new java.awt.Color(255, 255, 255));
        GENERO.setText("Genero:");
        getContentPane().add(GENERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        FECHA.setForeground(new java.awt.Color(255, 255, 255));
        FECHA.setText("FECHA DE EMISION");
        getContentPane().add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jButton2.setText("GENERAR BOLETA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 130, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 255));
        jLabel12.setText("Ingresar producto");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boleta/logo2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 230, 90));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("TOTAL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 40, 20));

        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 80, -1));
        jPanel1.add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));
        jPanel1.add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));
        jPanel1.add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, -1));

        jLabel5.setText("   PRECIO              CANTIDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 20));
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, -1));

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, -1));

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, -1));

        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        jPanel1.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, -1));

        ttotal.setText("t.total");
        jPanel1.add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 40, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 290, 120));

        CALCULARTOTAL1.setText("CALCULAR TOTAL");
        CALCULARTOTAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARTOTAL1ActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULARTOTAL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boleta/moto-bmw-f800-predator.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         boleta3 nf=new boleta3();
        nf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
   
    }//GEN-LAST:event_T1ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void CALCULARTOTAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARTOTAL1ActionPerformed
        double c,p,to;
        p=(double) Integer.parseInt(P1.getText());
        c=(double) Integer.parseInt(C1.getText());
        to=p*c;
        T1.setText(""+to);  
        double c1,p1,to1;
        p1=(double) Integer.parseInt(P2.getText());
        c1=(double) Integer.parseInt(C2.getText());
        to1=p1*c1;
        T2.setText(""+to1);  
        double c2,p2,to2;
        p2=(double) Integer.parseInt(P3.getText());
        c2=(double) Integer.parseInt(C3.getText());
        to2=p2*c2;
        T3.setText(""+to2); 
        double n1,n2,n3,tt;
        n1=(double) Integer.parseInt(T1.getText());
        n2=(double) Integer.parseInt(T2.getText());
        n3=(double) Integer.parseInt(T3.getText());
        tt=n1+n2+n3;
        T4.setText(""+tt);
    }//GEN-LAST:event_CALCULARTOTAL1ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOLETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOLETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOLETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOLETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOLETA2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField C3;
    private javax.swing.JButton CALCULARTOTAL1;
    private javax.swing.JLabel DIREC;
    private javax.swing.JLabel EDAD;
    private javax.swing.JLabel FECHA;
    private javax.swing.JLabel GENERO;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P2;
    private javax.swing.JTextField P3;
    private javax.swing.JLabel PROFESION;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JLabel TEL;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel ttotal;
    // End of variables declaration//GEN-END:variables

    private static class dicc {

        private static int size() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static Object get(int i) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void add(palabra palabra) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public dicc() {
        }
    }

    private static class palabra {

        public palabra(String parte, String parte0) {
        }
    }
}
